name: Agendador de Coleta de Vagas

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 9h (horário de Brasília, 12h UTC)
  workflow_dispatch:      # Permite rodar manualmente via botão no GitHub

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clona o repositório
        uses: actions/checkout@v3

      - name: Debug - verifica diretório atual e arquivos
        run: |
          pwd
          ls -l

      - name: Verifica arquivos no diretório atual
        run: ls -la

      - name: Configura ambiente Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Executa pipeline completo
        run: python main.py

      - name: Salva dados atualizados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          git commit -m "Atualiza dados - execução automática"
          git push
